name: Build and Push to DockerHub

on:
  push: 
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/myapacheapplication:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    # Create deployment package (deploy.zip)         
    - name: Create deploy.zip
      run: zip -r deploy.zip . -x '*.git*'

    # Deploy App to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MyApacheApplication
        environment_name: Myapacheapplication-env-2
        version_label: 1.1
        region: eu-north-1
     # Deploy to new package
        deployment_package: deploy.zip
